{{- if or (.Values.global.ingress.basicAuth.enabled) (.Values.ingress.basicAuth.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  labels:
    app: {{ template "name" . }}
  annotations:
    strategy.spinnaker.io/versioned: 'false'
type: Opaque
stringData:
  auth: |
    {{- if .Values.ingress.basicAuth.users }}
    {{- range $key, $value := .Values.ingress.basicAuth.users }}
    {{ htpasswd $key $value }}
    {{- end }}
    {{- else }}
    {{- range $key, $value := .Values.global.ingress.basicAuth.users }}
    {{ htpasswd $key $value }}
    {{- end }}
    {{- end }}
{{- end }}