apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-env-var
  annotations:
    strategy.spinnaker.io/versioned: 'false'
    strategy.spinnaker.io/replace: 'true'
  labels:
    app: {{ template "name" . }}
    {{- include "labels" . | nindent 4 }}
data:
  GIT_PR_NAMESPACE: "{{- if .Values.global.git.pullRequest.id }}pr-{{ .Values.global.git.pullRequest.id }}{{- else }}branch-{{ .Values.global.git.branchSlug }}{{- end }}"
  GIT_BRANCH: {{ .Values.global.git.branchSlug | quote }}
  GIT_PR_NUM: "{{- if .Values.global.git.pullRequest.id }}{{ .Values.global.git.pullRequest.id }}{{- else }}{{ .Values.global.git.branchSlug }}{{- end }}"
  PHYSICAL_ENV: {{ .Values.global.env | quote }}
{{- if .Values.global.deployment.env }}
  {{- range $name, $value := .Values.global.deployment.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.env }}
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}