{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    {{- include "labels" . | nindent 4 }}
type: Opaque
  {{- with .Values.secrets }}
stringData:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}