[program:blackfire]
command=blackfire agent:start
user=root
autostart=false
autorestart=false
startsecs=5
startretries=1000
stopsignal=QUIT
stopwaitsecs=60
stdout_events_enabled=true
stderr_events_enabled=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
