[program:frontend]
command=npm run dev
user=root
directory=/var/www/frontend
environment=HOME="/var/www"
autostart=%(ENV_AUTOSTART_APPS)s
autorestart=%(ENV_AUTOSTART_APPS)s
startsecs=5
startretries=1000
stopsignal=TERM
stdout_events_enabled=true
stderr_events_enabled=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
