apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: {{ template "name" . }}
  name: {{ template "fullname" . }}
spec:
  dataSource:
    name: {{ template "fullname" . }}
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.snapshot.size }}
  storageClassName: premium-rwo